<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Active' => 'Activo',
    'Are you sure you want to delete this user?' => '¿Está seguro que desea eliminar este usuario?',
    'Banned' => 'Bloqueado',
    'Bind to IP' => 'Enlazar a IP',
    'Browser' => 'Navegador',
    'Change own password' => 'Cambiar mi propia contraseña',
    'Change password' => 'Cambiar contraseña de usuario',
    'Changing password' => 'Cambiando contraseña',
    'Changing password for user: ' => 'Cambiando contraseña para el usuario: ',
    'Child permissions' => 'Permisos hijos',
    'Child roles' => 'Roles hijos',
    'Code' => 'Código',
    'Confirmation Token' => 'Token de confirmación',
    'Create' => 'Crear',
    'Created' => 'Creado',
    'Creating permission group' => 'Creación de grupo de permisos',
    'Current password' => 'Contraseña actual',
    'Data' => 'Dato',
    'Delete' => 'Eliminar',
    'Description' => 'Descripción',
    'E-mail' => 'Correo electrónico',
    'E-mail confirmed' => 'Correo confirmado',
    'E-mail with activation link has been sent to <b>{email}</b>. This link will expire in {minutes} min.' => 'Un correo electrónico con un enlace de activación ha sido enviado a <b>{email}</b>. El enlace expirará en {minutes} minutos.',
    'Edit' => 'Editar',
    'Editing' => 'Editando',
    'Editing permission group' => 'Editando grupo de permisos',
    'Editing permission: ' => 'Editando permiso: ',
    'Editing role: ' => 'Editando rol: ',
    'Editing user: ' => 'Editando usuario: ',
    'For example: 123.34.56.78, 168.111.192.12' => 'Por ejemplo: 123.34.56.78, 168.111.192.12',
    'Group' => 'Grupo',
    'ID' => 'ID',
    'Inactive' => 'Inactivo',
    'IP' => 'IP',
    'Language' => 'Idioma',
    'Login' => 'Inicio de sesión',
    'Username' => 'Nombre de usuario',
    'Name' => 'Nombre',
    'OS' => 'Sistema Operativo',
    'Password' => 'Contraseña',
    'Password has been changed' => 'La contraseña ha sido cambiada',
    'Permission creation' => 'Creación de permisos',
    'Permission groups' => 'Grupos de permisos',
    'Permissions' => 'Permisos',
    'Permissions for role:' => 'Permisos para el rol:',
    'Refresh routes' => 'Actualizar rutas',
    'Refresh routes (and delete unused)' => 'Actualizar rutas (y eliminar sin uso)',
    'Registration IP' => 'IP de registro',
    'Repeat password' => 'Repetir contraseña',
    'Reset' => 'Restablecer',
    'Role creation' => 'Creación de rol',
    'Roles' => 'Roles',
    'Roles and permissions' => 'Roles y permisos',
    'Roles and permissions for user:' => 'Roles y permisos para el usuario:',
    'Routes that are not exists in this application will be deleted. Do not recommended for application with "advanced" structure, because frontend and backend have they own set of routes.' => 'Se eliminarán rutas que no existan en esta aplicación. No se recomienda para aplicaciones con estructura "avanzada", porque el frontend y el backend tienen su propio conjunto de rutas.',
    'Rule' => 'Regla',
    'Save' => 'Guardar',
    'Saved' => 'Guardado',
    'Search' => 'Buscar',
    'Search route' => 'Buscar ruta',
    'Settings for permission' => 'Configuración de permiso',
    'Show all' => 'Mostrar todos',
    'Show only selected' => 'Mostrar solo seleccionados',
    'Status' => 'Estado',
    'Superadmin' => 'Superadmin',
    'Token' => 'Token',
    'Too many attempts' => 'Demasiados intentos',
    'Type' => 'Tipo',
    'Updated' => 'Actualizado',
    'User' => 'Usuario',
    'User agent' => 'Agente de usuario',
    'User creation' => 'Creación de usuario',
    'Users' => 'Usuarios',
    'Visit Time' => 'Fecha de visita',
    'Visit log' => 'Registro de visitas',
    'Wrong format. Enter valid IPs separated by comma' => 'Formato incorrecto. Ingrese IPs válidas separadas por coma.', 
    'Wrong password' => 'Contraseña incorrecta',
    'You can not change own permissions' => 'No puede cambiar sus propios permisos',
];
